Make server port configurable through environment variable LK_JWT_PORT, default 8080
element-hq/lk-jwt-service pull request #17
Opened 2024-03-09 21:27 UTC by rockaport

fixes #16

2024-03-11 07:57 UTC, fkwp requested changes
Hi @rockaport ,

thx for the contribution. In general, lgtm. One small nit. Can you pls update README.md as well?

2024-03-11 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/element-hq/lk-jwt-service?pullRequest=17) <br/>All committers have signed the CLA.

2024-03-14 11:33 UTC, rockaport commented
> Hi @rockaport ,
> 
> thx for the contribution. In general, lgtm. One small nit. Can you pls update README.md as well?

Done, thanks for the review.

2024-03-19 08:07 UTC, fkwp approved these changes

2024-03-19 08:32 UTC, merged